#版本信息
QTCREATOR_VERSION = 4.10.82
#插件所兼容的 Qt Creator 版本
QTCREATOR_COMPAT_VERSION = 4.10.82
QTCREATOR_DISPLAY_VERSION = 4.11.0-beta1
QTCREATOR_COPYRIGHT_YEAR = 2019
#指定的是 git 的分支
BINARY_ARTIFACTS_BRANCH = master

IDE_DISPLAY_NAME = Qt Creator
#指定的qtcreator exe名称
IDE_ID = qtcreator
IDE_CASED_ID = QtCreator

PRODUCT_BUNDLE_ORGANIZATION = org.qt-project
PROJECT_USER_FILE_EXTENSION = .user
